# Generated by Django 5.2.1 on 2025-05-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture_id',
            field=models.CharField(blank=True),
        ),
        migrations.CreateModel(
            name='project_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junoapi.project')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junoapi.team')),
            ],
        ),
    ]
