# Generated by Django 5.2.1 on 2025-05-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0003_rename_project_team_projectteam_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attatchment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attatchment', to='junoapi.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='junoapi.task'),
        ),
    ]
