# Generated by Django 5.2.1 on 2025-05-26 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0004_alter_attatchment_task_id_alter_comment_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=2048)),
                ('file_name', models.CharField(max_length=150)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='junoapi.task')),
                ('uploadedby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.DeleteModel(
            name='Attatchment',
        ),
    ]
