# Generated by Django 5.2.1 on 2025-06-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0005_attachment_delete_attatchment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
