# Generated by Django 5.2.1 on 2025-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0006_alter_task_due_date_alter_task_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
