# Generated by Django 5.2.1 on 2025-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0007_alter_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
