# Generated by Django 5.2.1 on 2025-08-07 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0008_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
