# Generated by Django 5.2.1 on 2025-08-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0009_remove_user_team_id_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cognito_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
