# Generated by Django 5.2.1 on 2025-08-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0012_alter_comment_user_id_alter_project_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uploadedby_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
