# Generated by Django 5.2.1 on 2025-08-26 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0013_alter_attachment_uploadedby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='productowner_userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_product_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
