# Generated by Django 5.2.1 on 2025-08-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junoapi', '0014_alter_team_productowner_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
